version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g yarn typescript
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - yarn.lock
    - package.json
    - 'build/**/*'
    - '.platform/**/*' # AWS Elastic Beanstalk configuration files
    - '.ebextensions/**/*' # AWS Elastic Beanstalk configuration files

discard-paths: no