# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm prune --production
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*
    - config/**/*
    - package.json
    - package-lock.json
    - tsconfig.json
    - server.ts
    - node_modules/**/*
  name: raisefundsbackend-$(date +%Y-%m-%d-%H-%M-%S)