GET http://localhost:8000/user/volunteers
Content-Type: application/json
{
    "Authorization" : "wefqwef"
}

####

POST http://localhost:8000/optVerification
Content-Type: application/json
